src/Entity/Batch.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity]
class Batch
{
    #[ORM\Column(type: 'integer')]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'AUTO')]
    private int $id;

    #[ORM\Column(type: 'string', nullable: true)]
    private string $name = '';

    /** @var Collection | Action[] */
    #[ORM\ManyToMany(targetEntity: Action::class)]
    private Collection $actions;

    #[ORM\Column(type: 'integer', nullable: true)]
    private int $delay = 0;

    /** @var Collection | Task[] */
    #[ORM\OneToMany(mappedBy: 'batch', targetEntity: Task::class)]
    private $tasks;

    #[ORM\Column(type: 'string', nullable: true)]
    private ?string $file = null;

    public function getId(): int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }

    public function getActions(): Collection
    {
        return $this->actions;
    }
    
    public function setActions(Collection $actions):void
    {
        $this->actions = $actions;
    }

    public function getDelay(): int
    {
        return $this->delay;
    }

    public function setDelay(int $delay): void
    {
        $this->delay = $delay;
    }

    public function getTasks(): Collection|array
    {
        return $this->tasks;
    }

    public function setTasks(Collection|array $tasks): void
    {
        $this->tasks = $tasks;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(?string $file): void
    {
        $this->file = $file;
    }

    public function __toString() : string
    {
        return $this->name;
    }
}

src/Entity/Task.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity]
class Task
{
    const STATUS_CREATED = 'CREATED';
    const STATUS_SUCCESS = 'SUCCESS';
    const STATUS_FAILURE = 'FAILURE';

    const ACTION_TYPES = [
        self::STATUS_CREATED,
        self::STATUS_SUCCESS,
        self::STATUS_FAILURE
    ];

    #[ORM\Column(type: 'integer')]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'AUTO')]
    private int $id;

    #[ORM\ManyToOne(targetEntity: Action::class)]
    private Action $action;

    #[ORM\ManyToOne(cascade: ["persist"], targetEntity: Batch::class, inversedBy: 'tasks')]
    private ?Batch $batch = null;

    #[ORM\Column(type: 'json', nullable: true)]
    private $data;

    #[ORM\Column(type: 'string', nullable: true)]
    private string $status = 'CREATED';

    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $result = '';

    /** @var Task|null */
    #[ORM\OneToOne(mappedBy: 'previous', targetEntity: Task::class)]
    private Task|null $next;

    /** @var Task */
    #[ORM\OneToOne(inversedBy: 'next', targetEntity: Task::class)]
    #[ORM\JoinColumn(onDelete: "CASCADE")]
    private Task|null $previous;

    #[ORM\Column(type: 'array', nullable: true)]
    private ?array $logs;

    public function getId(): int
    {
        return $this->id;
    }

    public function getBatch(): ?Batch
    {
        return $this->batch;
    }

    public function setBatch(Batch $batch): void
    {
        $this->batch = $batch;
    }

    public function getAction(): Action
    {
        return $this->action;
    }

    public function setAction(Action $action): void
    {
        $this->action = $action;
    }

    public function getData()
    {
        return $this->data;
    }

    public function setData($data): void
    {
        $this->data = $data;
    }

    public function mergeData($data): void
    {
        $this->data = (object) array_merge((array) $this->data, (array) $data);
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    public function getResult(): ?string
    {
        return $this->result;
    }

    public function isObject(): bool
    {
        return !!json_decode($this->result);
    }

    public function getResultParsed(): mixed
    {
        if (!$this->result) {
            return '';
        }
        return json_decode($this->result, true) ?? 'UNABLE TO PARSE';
    }

    public function setResult(?string $result): void
    {
        $this->result = $result;
    }

    public function getNext(): Task|null
    {
        return $this->next;
    }

    public function setNext(Task $next): void
    {
        $this->next = $next;
    }

    public function getPrevious(): Task|null
    {
        return $this->previous;
    }

    public function setPrevious(Task|null $previous): void
    {
        $this->previous = $previous;
    }
    
    public function getLogs(): ?array
    {
        return $this->logs;
    }

    public function addLogs($log):void
    {
        $this->logs[] = $log;
    }

    public function setLogs(?array $logs):void
    {
        $this->logs = $logs;
    }

    public function getIcon(): string
    {
        switch ($this->status) {
            case self::STATUS_SUCCESS:
                return 'check-circle';
            case self::STATUS_FAILURE:
                return 'exclamation-circle';
            default:
                return 'hourglass-start';
        }
    }

    public function getColor(): string
    {
        switch ($this->status) {
            case self::STATUS_FAILURE:
                return 'danger';
            default:
                return '';
        }
    }

    public function __toString(): string
    {
        return $this->id;
    }

}

src/Controller/BatchController.php
<?php

namespace App\Controller;

use App\Entity\Batch;
use App\Entity\Task;
use App\Message\BatchMessage;
use App\Message\TaskMessage;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Routing\Annotation\Route;

const BATCH_SIZE = 100;

#[Route('/batches', name: 'batches_')]
class BatchController extends AbstractController
{
    #[Route('/{id}/result', name: 'result')]
    public function result(Batch $batch, ManagerRegistry $registry): Response
    {
        $taskRepo = $registry->getManager()->getRepository(Task::class);
        $success = $taskRepo->count(['batch' => $batch, 'status' => Task::STATUS_SUCCESS]);
        $failure = $taskRepo->count(['batch' => $batch, 'status' => Task::STATUS_FAILURE]);
        return $this->render('/batch/result.html.twig', [
            'batch' => $batch,
            'success' => $success,
            'failure' => $failure
        ]);
    }

    #[Route('/{id}/process', name: 'process')]
    public function process(Batch $batch, Request $request, ParameterBagInterface $bag, ManagerRegistry $registry, MessageBusInterface $bus): Response
    {
        $offset = $batch->getTasks()->count();
        $em = $registry->getManager();
        $handle = fopen($bag->get('kernel.project_dir') . "/public/data/" . $batch->getFile(), "r");
        if ($handle !== false) {
            $count = 0;
            $headers = [];
            while (($data = fgetcsv($handle, 0, ",")) !== false) {
                $count++;
                if ($count == 1) {
                    $headers = $data;
                    continue;
                }
                if ($count < $offset) {
                    continue;
                }
                $previous = null;
                foreach ($batch->getActions() as $action) {
                    $task = new Task();
                    $task->setBatch($batch);
                    $task->setAction($action);
                    $result = [];
                    for ($i = 0; $i < count($headers); $i++) {
                        $result[$headers[$i]] = $data[$i];
                    }
                    $task->setData($result);
                    if ($previous) {
                        $task->setPrevious($previous);
                    }
                    $previous = $task;
                    $em->persist($task);
                }
                if ($count % BATCH_SIZE == 0) {
                    $em->flush();
                    $em->clear();
                    $batch = $em->getRepository(Batch::class)->find($batch->getId());
                }
            }
            fclose($handle);
        }
        $em->flush();
        $bus->dispatch(new BatchMessage($batch->getId()));

        $route = $request->headers->get('referer');
        return $this->redirect($route);
    }

    #[Route('/{id}/retry', name: 'retry')]
    public function retry(Batch $batch, Request $request, ManagerRegistry $registry, MessageBusInterface $bus): Response
    {
        $em = $registry->getManager();
        /** @var Task $task */
        foreach ($batch->getTasks() as $task) {
            if ($task->getStatus() !== Task::STATUS_SUCCESS) {
                $task->setStatus(Task::STATUS_CREATED);
                $task->setResult(null);
                $bus->dispatch(new TaskMessage($task->getId()));
            }
        }
        $em->flush();

        $route = $request->headers->get('referer');
        return $this->redirect($route);
    }

    #[Route('/{id}/reset', name: 'reset')]
    public function reset(Batch $batch, Request $request, ManagerRegistry $registry, MessageBusInterface $bus): Response
    {
        $em = $registry->getManager();
        /** @var Task $task */
        foreach ($batch->getTasks() as $task) {
            $task->setStatus(Task::STATUS_CREATED);
            $task->setResult(null);
            $bus->dispatch(new TaskMessage($task->getId()));
        }
        $em->flush();

        $route = $request->headers->get('referer');
        return $this->redirect($route);
    }

}

templates/batch/result.html.twig
{% extends '@!EasyAdmin/layout.html.twig' %}

{% block content_title %}Results {{ batch.name }}{% endblock %}

{% block page_actions %}
    <div class="global-actions">
        <input type=button value="Copy to Clipboard" class="action-new btn btn-primary" onClick="copytable('results')">
    </div>

    <script type="text/javascript">
        function copytable(el) {
            var urlField = document.getElementById(el)
            var range = document.createRange()
            range.selectNode(urlField)
            window.getSelection().addRange(range)
            document.execCommand('copy')
        }
    </script>
{% endblock %}

{% block main %}
    <style>
        .unselectable {
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -khtml-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            -o-user-select:none;
            user-select: none;
        }
    </style>

    {% set total = batch.tasks.count %}
    <div class="progress">
        {% set percentage = success / total * 100 %}
        <div class="progress-bar bg-success" role="progressbar" style="width: {{ percentage }}%" aria-valuenow="{{ percentage }}" aria-valuemin="0" aria-valuemax="100">
            {{ percentage|round(1, 'ceil') }}%
        </div>
        {% set percentage = failure / total * 100 %}
        <div class="progress-bar bg-danger" role="progressbar" style="width: {{ percentage }}%" aria-valuenow="{{ percentage }}" aria-valuemin="0" aria-valuemax="100">
            {{ percentage|round(1, 'ceil') }}%
        </div>
    </div>

    <br>
    {% set firstTask = batch.tasks[0] %}
    <table class="table" id="results">
        <thead>
        <tr>
            <th class="unselectable">Id</th>
            {% for key,value in firstTask.data %}
                <th>{{ key }}</th>
            {% endfor %}
            <th class="unselectable">Status</th>
            {% for key,value in firstTask.resultParsed %}
                <th>{{ key }}</th>
            {% else %}
                <th>Result</th>
            {% endfor %}
            <th class="unselectable"></th>
            {% if firstTask.next  %}
                <th class="unselectable">Status</th>
                <th>Result</th>
                <th class="unselectable"></th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for task in batch.tasks %}
            {% if not task.previous %}
                <tr class="table-{{task.color}}">
                    <td class="unselectable">{{ task.id }}</td>
                    {% for key,value in task.data %}
                        <td>{{ value }}</td>
                    {% endfor %}
                    <td class="unselectable"><i class="fa fa-lg fw fa-{{ task.icon }}"></i></td>
                    {% if task.status == 'SUCCESS' %}
                        {% for key,value in task.resultParsed %}
                            <td>
                                {% if value is iterable %}
                                <table class="small">
                                    {% for k,v in value %}
                                        <th style="text-align: center; writing-mode: vertical-lr; transform: rotate(180deg);">{{ k }}</th>
                                        <td>
                                            {% if v is iterable %}
                                                {% for k_,v_ in v %}
                                                    {% if v_ is iterable %}{{ v|json_encode(constant('JSON_PRETTY_PRINT')) }}{% endif %}
                                                    <b>{{k_}}:</b>{{v_}}<br>
                                                {% endfor %}
                                            {% endif %}
                                        </td>
                                    {% endfor %}
                                </table>
                                {% else %}
                                    {{ value }}
                                {% endif %}
                            </td>
                        {% else %}
                            <td>{{ task.result }}</td>
                        {% endfor %}
                    {% else %}
                        <td>N/A</td>
                    {% endif %}
                    <td class="unselectable"><a href="{{ ea_url()
                                     .setController('App\\Controller\\Admin\\TaskCrudController')
                                     .setAction('result')
                                     .setEntityId(task.id) }}">Details</a></td>
                    {% if task.next %}
                        <td class="unselectable"><i class="fa fa-lg fw fa-{{ task.icon }}"></i></td>
                        {% if task.next.status == 'SUCCESS' %}
                            {% for key,value in task.next.resultParsed %}
                                <td>
                                    {% if value is iterable %}
                                    <table class="small">
                                        {% for k,v in value %}
                                            <th style="text-align: center; writing-mode: vertical-lr; transform: rotate(180deg);">{{ k }}</th>
                                            <td>
                                                {% if v is iterable %}
                                                    {% for k_,v_ in v %}
                                                        {% if v_ is iterable %}{{ v|json_encode(constant('JSON_PRETTY_PRINT')) }}{% endif %}
                                                        <b>{{k_}}:</b>{{v_}}<br>
                                                    {% endfor %}
                                                {% endif %}
                                            </td>
                                        {% endfor %}
                                    </table>
                                    {% else %}
                                        {{ value }}
                                    {% endif %}
                                </td>
                            {% else %}
                                <td>{{ task.next.result }}</td>
                            {% endfor %}
                        {% else %}
                            <td>N/A</td>
                        {% endif %}
                        <td class="unselectable"><a href="{{ ea_url()
                                         .setController('App\\Controller\\Admin\\TaskCrudController')
                                         .setAction('result')
                                         .setEntityId(task.next.id) }}">Details</a></td>
                    {% endif %}
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
{% endblock %}